### ISSUE TITLE
Notes with newlines not being imported into Evernote

### ISSUE THREAD

**Issue by kcereru** [tanrax/standard-notes-to-evernote-or-joplin#6]
On trying to import several thousand notes into Evernote from Standard Notes, I found that any note containing a newline was being imported with blank content.

The source of this seems to be the `<br>` tag they're being converted to. From the docs at https://dev.evernote.com/doc/articles/enml.php:
> Because ENML is based on XHTML and must strictly comply with the ENML DTD, there are a couple of things you should keep in mind. Every tag must be closed and properly balanced, so instead of using `<hr>`, you must use `<hr/>`. Tag names must be all lowercase.

Looks like changing the `<br>` tag to `<br />` fixes this. I'll make a PR shortly with the fix I'm using.

**Comment by tanrax** [comment]
Fantastic! I apply it. Thank you for your research and implementation efforts.

**Comment by kcereru** [comment]
No worries! Thanks for the script, it's been a huge help.
