### ISSUE TITLE
Standard Notes No Longer Exports TXT

### ISSUE THREAD

**Issue by jcady** [tanrax/standard-notes-to-evernote-or-joplin#8]
It looks like Standard Notes changed how they handle backups. They now only export a ZIP file with all your notes in separate TXT files, not a single TXT file.

![image](https://user-images.githubusercontent.com/5055534/118738100-1c09a300-b7fb-11eb-9a95-3afebf507260.png)

**Comment by tanrax** [comment]
Even in the option: Decrypted? What do you want to show me with the screenshot.

**Comment by jcady** [comment]
Yep, even with decrypted. Screenshot is just to show you that it has changed since you posted your tutorial (e.g. it's now called "Data Backups" instead of "Data Archives").

**Comment by tanrax** [comment]
Thanks for the heads-up!, but unfortunately I will not be able to perform the upgrade 😥. I hope someone new will step up and make a pull request.
